### ISSUE TITLE
ArgumentError: Unknown color name with the console reporter

### ISSUE THREAD

**Issue by thedrow** [whitesmith/rubycritic#206]
```
ArgumentError: Unknown color name, valid names: aqua, aquamarine, mediumaquamarine, azure, beige, bisque, black, blanchedalmond, blue, darkblue, lightblue, mediumblue, aliceblue, cadetblue, dodgerblue, midnightblue, navyblue, powderblue, royalblue, skyblue, deepskyblue, lightskyblue, slateblue, darkslateblue, mediumslateblue, steelblue, lightsteelblue, brown, rosybrown, saddlebrown, sandybrown, burlywood, chartreuse, chocolate, coral, lightcoral, cornflower, cornsilk, crimson, cyan, darkcyan, lightcyan, firebrick, fuchsia, gainsboro, gold, goldenrod, darkgoldenrod, lightgoldenrod, palegoldenrod, gray, darkgray, dimgray, lightgray, slategray, lightslategray, webgray, green, darkgreen, lightgreen, palegreen, darkolivegreen, yellowgreen, forestgreen, lawngreen, limegreen, seagreen, darkseagreen, lightseagreen, mediumseagreen, springgreen, mediumspringgreen, webgreen, honeydew, indianred, indigo, ivory, khaki, darkkhaki, lavender, lavenderblush, lemonchiffon, lime, linen, magenta, darkmagenta, maroon, webmaroon, mintcream, mistyrose, moccasin, oldlace, olive, olivedrab, orange, darkorange, orchid, darkorchid, mediumorchid, papayawhip, peachpuff, peru, pink, deeppink, lightpink, hotpink, plum, purple, mediumpurple, rebeccapurple, webpurple, red, darkred, orangered, mediumvioletred, palevioletred, salmon, darksalmon, lightsalmon, seashell, sienna, silver, darkslategray, snow, tan, teal, thistle, tomato, turquoise, darkturquoise, mediumturquoise, paleturquoise, violet, darkviolet, blueviolet, wheat, white, antiquewhite, floralwhite, ghostwhite, navajowhite, whitesmoke, yellow, lightyellow, greenyellow
  /home/ubuntu/5rr_v2/vendor/bundle/ruby/2.2.0/gems/rainbow-2.1.0/lib/rainbow/color.rb:125:in `initialize'
  /home/ubuntu/5rr_v2/vendor/bundle/ruby/2.2.0/gems/rainbow-2.1.0/lib/rainbow/color.rb:21:in `new'
  /home/ubuntu/5rr_v2/vendor/bundle/ruby/2.2.0/gems/rainbow-2.1.0/lib/rainbow/color.rb:21:in `build'
  /home/ubuntu/5rr_v2/vendor/bundle/ruby/2.2.0/gems/rainbow-2.1.0/lib/rainbow/presenter.rb:21:in `color'
  (erb):1:in `render'
  /opt/circleci/ruby/ruby-2.2.0/lib/ruby/2.2.0/erb.rb:863:in `eval'
  /opt/circleci/ruby/ruby-2.2.0/lib/ruby/2.2.0/erb.rb:863:in `result'
  /home/ubuntu/5rr_v2/vendor/bundle/ruby/2.2.0/gems/rubycritic-3.1.2/lib/rubycritic/generators/text/list.rb:29:in `render'
  /home/ubuntu/5rr_v2/vendor/bundle/ruby/2.2.0/gems/rubycritic-3.1.2/lib/rubycritic/generators/console_report.rb:13:in `block in generate_report'
  /home/ubuntu/5rr_v2/vendor/bundle/ruby/2.2.0/gems/rubycritic-3.1.2/lib/rubycritic/generators/console_report.rb:12:in `map'
  /home/ubuntu/5rr_v2/vendor/bundle/ruby/2.2.0/gems/rubycritic-3.1.2/lib/rubycritic/generators/console_report.rb:12:in `generate_report'
  /home/ubuntu/5rr_v2/vendor/bundle/ruby/2.2.0/gems/rubycritic-3.1.2/lib/rubycritic/reporter.rb:5:in `generate_report'
  /home/ubuntu/5rr_v2/vendor/bundle/ruby/2.2.0/gems/rubycritic-3.1.2/lib/rubycritic/commands/default.rb:28:in `report'
  /home/ubuntu/5rr_v2/vendor/bundle/ruby/2.2.0/gems/rubycritic-3.1.2/lib/rubycritic/commands/default.rb:18:in `execute'
  /home/ubuntu/5rr_v2/vendor/bundle/ruby/2.2.0/gems/rubycritic-3.1.2/lib/rubycritic/cli/application.rb:19:in `execute'
  /home/ubuntu/5rr_v2/vendor/bundle/ruby/2.2.0/gems/rubycritic-3.1.2/bin/rubycritic:10:in `<top (required)>'
  /home/ubuntu/5rr_v2/vendor/bundle/ruby/2.2.0/bin/rubycritic:23:in `load'
  /home/ubuntu/5rr_v2/vendor/bundle/ruby/2.2.0/bin/rubycritic:23:in `<top (required)>'
```

Can we fix this ASAP? It's failing my CI.

**Comment by thedrow** [comment]
Seems like `light_red` is gone from the valid colors list. Any idea what to do?

**Comment by Onumis** [comment]
I think `orange` is a good replacement for `light_red` :)

**Comment by Onumis** [comment]
@thedrow published!

**Comment by thedrow** [comment]
@Onumis You forgot to tag :)
