### ISSUE TITLE
String can't be coerced into Fixnum (TypeError)

### ISSUE THREAD

**Issue by kyledecot** [whitesmith/rubycritic#211]
When running `rubycritic -ms 70 --no-browser` for my application I am receiving the following:

```
/usr/local/bundle/gems/rubycritic-3.1.0/lib/rubycritic/analysis_summary.rb:33:in `+': String can't be coerced into Fixnum (TypeError)
	from /usr/local/bundle/gems/rubycritic-3.1.0/lib/rubycritic/analysis_summary.rb:33:in `block in churns'
	from /usr/local/bundle/gems/rubycritic-3.1.0/lib/rubycritic/analysis_summary.rb:33:in `each'
	from /usr/local/bundle/gems/rubycritic-3.1.0/lib/rubycritic/analysis_summary.rb:33:in `inject'
	from /usr/local/bundle/gems/rubycritic-3.1.0/lib/rubycritic/analysis_summary.rb:33:in `churns'
	from /usr/local/bundle/gems/rubycritic-3.1.0/lib/rubycritic/analysis_summary.rb:27:in `generate_for'
	from /usr/local/bundle/gems/rubycritic-3.1.0/lib/rubycritic/analysis_summary.rb:15:in `block in generate'
	from /usr/local/bundle/gems/rubycritic-3.1.0/lib/rubycritic/analysis_summary.rb:14:in `each'
	from /usr/local/bundle/gems/rubycritic-3.1.0/lib/rubycritic/analysis_summary.rb:14:in `each_with_object'
	from /usr/local/bundle/gems/rubycritic-3.1.0/lib/rubycritic/analysis_summary.rb:14:in `generate'
	from /usr/local/bundle/gems/rubycritic-3.1.0/lib/rubycritic/analysis_summary.rb:6:in `generate'
	from /usr/local/bundle/gems/rubycritic-3.1.0/lib/rubycritic/core/analysed_modules_collection.rb:40:in `summary'
	from /usr/local/bundle/gems/rubycritic-3.1.0/lib/rubycritic/generators/html/overview.rb:16:in `initialize'
	from /usr/local/bundle/gems/rubycritic-3.1.0/lib/rubycritic/generators/html_report.rb:45:in `new'
	from /usr/local/bundle/gems/rubycritic-3.1.0/lib/rubycritic/generators/html_report.rb:45:in `overview_generator'
	from /usr/local/bundle/gems/rubycritic-3.1.0/lib/rubycritic/generators/html_report.rb:41:in `generators'
	from /usr/local/bundle/gems/rubycritic-3.1.0/lib/rubycritic/generators/html_report.rb:32:in `create_directories_and_files'
	from /usr/local/bundle/gems/rubycritic-3.1.0/lib/rubycritic/generators/html_report.rb:19:in `generate_report'
	from /usr/local/bundle/gems/rubycritic-3.1.0/lib/rubycritic/reporter.rb:5:in `generate_report'
	from /usr/local/bundle/gems/rubycritic-3.1.0/lib/rubycritic/commands/default.rb:28:in `report'
	from /usr/local/bundle/gems/rubycritic-3.1.0/lib/rubycritic/commands/default.rb:18:in `execute'
	from /usr/local/bundle/gems/rubycritic-3.1.0/lib/rubycritic/cli/application.rb:19:in `execute'
	from /usr/local/bundle/gems/rubycritic-3.1.0/bin/rubycritic:10:in `<top (required)>'
	from /usr/local/bundle/bin/rubycritic:17:in `load'
	from /usr/local/bundle/bin/rubycritic:17:in `<main>'
```

I am using version `3.1.0`

**Comment by kyledecot** [comment]
Closing. Duplicate of #188
