### ISSUE TITLE
rubycritic command fails when a directory name ends in .rb

### ISSUE THREAD

**Issue by bbugh** [whitesmith/rubycritic#246]
I'm working on a project that has a **directory** named `compose_assets.rb`. When flog runs, it raises an error because it's trying to read it as a file. I'm guessing that rubycritic is supplying the list of files, but if not this might be a flog issue instead. I don't own the project so I can't change the directory.

```
/Users/bbugh/.rvm/gems/ruby-2.2.4/gems/flog-4.6.1/lib/flog.rb:178:in `binread': Is a directory @ io_fread - vendor/scripts/compose_assets.rb (Errno::EISDIR)
	from /Users/bbugh/.rvm/gems/ruby-2.2.4/gems/flog-4.6.1/lib/flog.rb:178:in `block in flog'
	from /Users/bbugh/.rvm/gems/ruby-2.2.4/gems/flog-4.6.1/lib/flog.rb:175:in `each'
	from /Users/bbugh/.rvm/gems/ruby-2.2.4/gems/flog-4.6.1/lib/flog.rb:175:in `flog'
	from /Users/bbugh/.rvm/gems/ruby-2.2.4/gems/rubycritic-3.2.3/lib/rubycritic/analysers/smells/flog.rb:35:in `add_smells_to'
	from /Users/bbugh/.rvm/gems/ruby-2.2.4/gems/rubycritic-3.2.3/lib/rubycritic/analysers/smells/flog.rb:21:in `block in run'
	from /Users/bbugh/.rvm/gems/ruby-2.2.4/gems/rubycritic-3.2.3/lib/rubycritic/core/analysed_modules_collection.rb:27:in `each'
	from /Users/bbugh/.rvm/gems/ruby-2.2.4/gems/rubycritic-3.2.3/lib/rubycritic/core/analysed_modules_collection.rb:27:in `each'
	from /Users/bbugh/.rvm/gems/ruby-2.2.4/gems/rubycritic-3.2.3/lib/rubycritic/analysers/smells/flog.rb:20:in `run'
	from /Users/bbugh/.rvm/gems/ruby-2.2.4/gems/rubycritic-3.2.3/lib/rubycritic/analysers_runner.rb:30:in `block in run'
	from /Users/bbugh/.rvm/gems/ruby-2.2.4/gems/rubycritic-3.2.3/lib/rubycritic/analysers_runner.rb:27:in `each'
	from /Users/bbugh/.rvm/gems/ruby-2.2.4/gems/rubycritic-3.2.3/lib/rubycritic/analysers_runner.rb:27:in `run'
	from /Users/bbugh/.rvm/gems/ruby-2.2.4/gems/rubycritic-3.2.3/lib/rubycritic/commands/default.rb:24:in `critique'
	from /Users/bbugh/.rvm/gems/ruby-2.2.4/gems/rubycritic-3.2.3/lib/rubycritic/commands/default.rb:19:in `execute'
	from /Users/bbugh/.rvm/gems/ruby-2.2.4/gems/rubycritic-3.2.3/lib/rubycritic/cli/application.rb:20:in `execute'
	from /Users/bbugh/.rvm/gems/ruby-2.2.4/gems/rubycritic-3.2.3/bin/rubycritic:10:in `<top (required)>'
	from /Users/bbugh/.rvm/gems/ruby-2.2.4/bin/rubycritic:23:in `load'
	from /Users/bbugh/.rvm/gems/ruby-2.2.4/bin/rubycritic:23:in `<main>'
```

**Comment by guilhermesimoes** [comment]
Great bug report.
This was actually a bug in `path_expander`, a dependency of Flog.
I've opened a PR in the Flog repository to bump the gem dependency.
In the meantime, you can fix this by running the following commands:

```
gem uninstall path_expander
gem install path_expander
```

If you added RubyCritic to your Gemfile, change the version of `path_expander`in your Gemfile.lock from `1.0.0` to `1.0.2`.
