### ISSUE TITLE
Not loading reek configuration file

### ISSUE THREAD

**Issue by ronyv89** [whitesmith/rubycritic#270]
I create a .reek.yml configuration file in my Rails application root directory. But rubycritic is not picking up this file for loading configuration

**Comment by luizkowalski** [comment]
I have the same issue. I created a config file as follow

```
detectors:
  NilCheck:
    enabled: false

  IrresponsibleModule:
    enabled: false

exclude_paths:
  - db/

directories:
  "app/controllers":
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
    UtilityFunction:
      enabled: false
  "app/mailers":
    InstanceVariableAssumption:
      enabled: false
```

but I still get lots of `InstanceVariableAssumption` warnings, for example
I'm using RubyCritic 3.4.0 on a MacOS with Ruby 2.5.1

**Comment by KurtRMueller** [comment]
Reek recently upgraded from version 4 to version 5 and, as such, changed the api for its configuration file. You can read about it here: https://github.com/troessner/reek/blob/master/docs/Reek-4-to-Reek-5-migration.md

Hopefully rubycritic updates it's reek dependency soon.

**Comment by Onumis** [comment]
We'll need to do a major release of rubycritic to avoid backward incompatibilities.
The newest version should also drop some old ruby versions...

**Comment by philCryoport** [comment]
Please re-open -- files `.reek.yml` and `config.reek` are both seemingly being ignored

Those two files both have the contents:
```
exclude_paths:
  - lib/templates/rails/scaffold_controller/controller.rb
```
...because Reek is freaking out about `<%- generate "pundit:policy", singular_name -%>` in the first line of that controller.rb file

* ruby 2.5.3 on WSL - installed with `rbenv`
* Brand new install of rubycritic (`gem install rubycritic` put in rubycritic 4.0.2)
* I have Reek 5.4.0 installed but the traceback is grabbing reek 5.3.2 -- see below

How do I get rubycritic to tell reek to pay attention to either `.reek.yml` or `config.reek` ? 


```
% rubycritic
warning: parser/current is loading parser/ruby25, which recognizes
warning: 2.5.5-compliant syntax, but you are running 2.5.3.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
  lib/templates/rails/scaffold_controller/controller.rb:1 :: parse error on value "<" (tLT)
  skipping lib/templates/rails/scaffold_controller/controller.rb
running flay smells
...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
running flog smells
.....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................#<Racc::ParseError: lib/templates/rails/scaffold_controller/controller.rb:1 :: parse error on value "<" (tLT)> at /home/USER/.rbenv/versions/2.5.3/lib/ruby/2.5.0/racc/parser.rb:528:in `on_error', /home/USER/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/ruby_parser-3.13.1/lib/ruby_parser_extras.rb:1179:in `on_error', /home/USER/.rbenv/versions/2.5.3/lib/ruby/2.5.0/racc/parser.rb:259:in `_racc_do_parse_c', /home/USER/.rbenv/versions/2.5.3/lib/ruby/2.5.0/racc/parser.rb:259:in `do_parse', /home/USER/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/ruby_parser-3.13.1/lib/ruby_parser_extras.rb:1086:in `block in process'

...stupid lemmings and their bad erb templates... skipping
.........................................................................................................................................................................................................................................................................................................................................................................................................................................................
running reek smells
.....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................Traceback (most recent call last):
        17: from /home/USER/.rbenv/versions/2.5.3/bin/rubycritic:23:in `<main>'
        16: from /home/USER/.rbenv/versions/2.5.3/bin/rubycritic:23:in `load'
        15: from /home/USER/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rubycritic-4.0.2/bin/rubycritic:10:in `<top (required)>'
        14: from /home/USER/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rubycritic-4.0.2/lib/rubycritic/cli/application.rb:21:in `execute'
        13: from /home/USER/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rubycritic-4.0.2/lib/rubycritic/commands/default.rb:19:in `execute'
        12: from /home/USER/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rubycritic-4.0.2/lib/rubycritic/commands/default.rb:24:in `critique'
        11: from /home/USER/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rubycritic-4.0.2/lib/rubycritic/analysers_runner.rb:27:in `run'
        10: from /home/USER/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rubycritic-4.0.2/lib/rubycritic/analysers_runner.rb:27:in `each'
         9: from /home/USER/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rubycritic-4.0.2/lib/rubycritic/analysers_runner.rb:30:in `block in run'
         8: from /home/USER/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rubycritic-4.0.2/lib/rubycritic/analysers/smells/reek.rb:16:in `run'
         7: from /home/USER/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rubycritic-4.0.2/lib/rubycritic/core/analysed_modules_collection.rb:32:in `each'
         6: from /home/USER/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rubycritic-4.0.2/lib/rubycritic/core/analysed_modules_collection.rb:32:in `each'
         5: from /home/USER/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rubycritic-4.0.2/lib/rubycritic/analysers/smells/reek.rb:17:in `block in run'
         4: from /home/USER/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rubycritic-4.0.2/lib/rubycritic/analysers/smells/reek.rb:30:in `add_smells_to'
         3: from /home/USER/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/reek-5.3.2/lib/reek/examiner.rb:61:in `smells'
         2: from /home/USER/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/reek-5.3.2/lib/reek/examiner.rb:93:in `run'
         1: from /home/USER/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/reek-5.3.2/lib/reek/examiner.rb:103:in `wrap_exceptions'
/home/USER/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/reek-5.3.2/lib/reek/examiner.rb:110:in `rescue in wrap_exceptions': Source 'lib/templates/rails/scaffold_controller/controller.rb' cannot be processed by Reek due to a syntax error in the source file. (Reek::Errors::SyntaxError)
```

**Comment by jose-quinones** [comment]
Hey @philCryoport is Rubycritic still not picking up your .reek.yml? I just added a .reek.yml to my project and it is working.
ruby version: 2.6.3
My Gemfile.lock:
```
    rubycritic (4.4.0)
      flay (~> 2.8)
      flog (~> 4.4)
      launchy (= 2.4.3)
      parser (>= 2.6.0)
      rainbow (~> 3.0)
      reek (~> 5.0, < 6.0)
      ruby_parser (~> 3.8)
      simplecov (>= 0.17.0)
      tty-which (~> 0.4.0)
      virtus (~> 1.0)
```

My .reek.yml:
```
directories:
  "app/controllers":
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
  "app/helpers":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  "app/models":
    InstanceVariableAssumption:
      enabled: false
```
