### ISSUE TITLE
Error parsing "&."

### ISSUE THREAD

**Issue by nunosilva800** [whitesmith/rubycritic#296]
```
ERROR: parsing ruby file app/models/admin/api/checkin_request.rb
Racc::ParseError: app/models/admin/api/checkin_request.rb:17 :: parse error on value "&." (error) at:
  /Users/nuno/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/racc/parser.rb:528:in `on_error'
  /Users/nuno/.rvm/gems/ruby-2.5.3/gems/ruby_parser-3.12.0/lib/ruby_parser_extras.rb:1175:in `on_error'
  /Users/nuno/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/racc/parser.rb:259:in `_racc_do_parse_c'
  /Users/nuno/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/racc/parser.rb:259:in `do_parse'
  /Users/nuno/.rvm/gems/ruby-2.5.3/gems/ruby_parser-3.12.0/lib/ruby_parser_extras.rb:1082:in `block in process'
```

sample code:
```ruby
 def initialize(params = {})
    @action = params['action']&.to_sym
  end
```

rubycritic 4.0.0
ruby 2.5.3

**Comment by Onumis** [comment]
same happens on rubycritic 3.5.2
