### ISSUE TITLE
undefined method `cost' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by abhitrivedi** [whitesmith/rubycritic#307]
Hi

Im getting an error while comparing with a branch (using `-b` option) or running in CI mode (using `-m` option). Backtrace attached below.

|            | Version |
|------------|---------|
| Ruby       | 2.5.5   |
| RubyCritic | 4.0.2   |
```
Traceback (most recent call last):
	23: from /home/atrivedi/.rbenv/versions/2.5.5/bin/rubycritic:23:in `<main>'
	22: from /home/atrivedi/.rbenv/versions/2.5.5/bin/rubycritic:23:in `load'
	21: from /home/atrivedi/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubycritic-4.0.2/bin/rubycritic:10:in `<top (required)>'
	20: from /home/atrivedi/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubycritic-4.0.2/lib/rubycritic/cli/application.rb:21:in `execute'
	19: from /home/atrivedi/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubycritic-4.0.2/lib/rubycritic/commands/compare.rb:20:in `execute'
	18: from /home/atrivedi/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubycritic-4.0.2/lib/rubycritic/commands/compare.rb:37:in `compare_branches'
	17: from /home/atrivedi/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubycritic-4.0.2/lib/rubycritic/commands/compare.rb:61:in `analyse_modified_files'
	16: from /home/atrivedi/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubycritic-4.0.2/lib/rubycritic/commands/default.rb:29:in `report'
	15: from /home/atrivedi/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubycritic-4.0.2/lib/rubycritic/reporter.rb:8:in `generate_report'
	14: from /home/atrivedi/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubycritic-4.0.2/lib/rubycritic/reporter.rb:8:in `each'
	13: from /home/atrivedi/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubycritic-4.0.2/lib/rubycritic/reporter.rb:9:in `block in generate_report'
	12: from /home/atrivedi/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubycritic-4.0.2/lib/rubycritic/generators/html_report.rb:20:in `generate_report'
	11: from /home/atrivedi/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubycritic-4.0.2/lib/rubycritic/generators/html_report.rb:33:in `create_directories_and_files'
	10: from /home/atrivedi/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubycritic-4.0.2/lib/rubycritic/generators/html_report.rb:33:in `each'
	 9: from /home/atrivedi/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubycritic-4.0.2/lib/rubycritic/generators/html_report.rb:35:in `block in create_directories_and_files'
	 8: from /home/atrivedi/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubycritic-4.0.2/lib/rubycritic/generators/html_report.rb:35:in `open'
	 7: from /home/atrivedi/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubycritic-4.0.2/lib/rubycritic/generators/html_report.rb:36:in `block (2 levels) in create_directories_and_files'
	 6: from /home/atrivedi/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubycritic-4.0.2/lib/rubycritic/generators/html/code_index.rb:27:in `render'
	 5: from /home/atrivedi/.rbenv/versions/2.5.5/lib/ruby/2.5.0/erb.rb:876:in `result'
	 4: from /home/atrivedi/.rbenv/versions/2.5.5/lib/ruby/2.5.0/erb.rb:876:in `eval'
	 3: from (erb):22:in `base_binding'
	 2: from /home/atrivedi/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubycritic-4.0.2/lib/rubycritic/core/analysed_modules_collection.rb:32:in `each'
	 1: from /home/atrivedi/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rubycritic-4.0.2/lib/rubycritic/core/analysed_modules_collection.rb:32:in `each'
(erb):28:in `block in base_binding': undefined method `cost' for nil:NilClass (NoMethodError)
```

**Comment by Adre** [comment]
I've had the same error in a similar situation using **RubyCritic 4.1.0** on **Ruby 2.6.3**.

I'm running the `rubycritic` command in the CLI with no arguments, but have the following `.rubycritic.yml` config:

```
mode_ci:
  enabled: true
branch: 'production'
path: 'rubycritic'
no_browser: false
threshhold_score: 1
minimum_score: 95
paths:
  - 'app/'
  - 'lib/'
```

The command analyses to code, but then fails around the point where it would generate the third html file:

```
$ rubycritic
Switched to branch 'master'
running flay smells
..
running flog smells
....................................................................................
running reek smells
....................................................................................
running complexity
....................................................................................
running attributes
....................................................................................
running churn
....................................................................................
New critique at file:////Volumes/work/rubycritic/compare/master/overview.html
Switched to branch 'critic'
running flay smells
....
running flog smells
...........................................................................................
running reek smells
...........................................................................................
running complexity
...........................................................................................
running attributes
...........................................................................................
running churn
...........................................................................................
New critique at file:////Volumes/work/rubycritic/compare/master/compare/critic/overview.html
Traceback (most recent call last):
	23: from /Users/adre/.gem/ruby/2.6.3/bin/rubycritic:23:in `<main>'
	22: from /Users/adre/.gem/ruby/2.6.3/bin/rubycritic:23:in `load'
	21: from /Users/adre/.gem/ruby/2.6.3/gems/rubycritic-4.1.0/bin/rubycritic:10:in `<top (required)>'
	20: from /Users/adre/.gem/ruby/2.6.3/gems/rubycritic-4.1.0/lib/rubycritic/cli/application.rb:21:in `execute'
	19: from /Users/adre/.gem/ruby/2.6.3/gems/rubycritic-4.1.0/lib/rubycritic/commands/compare.rb:20:in `execute'
	18: from /Users/adre/.gem/ruby/2.6.3/gems/rubycritic-4.1.0/lib/rubycritic/commands/compare.rb:37:in `compare_branches'
	17: from /Users/adre/.gem/ruby/2.6.3/gems/rubycritic-4.1.0/lib/rubycritic/commands/compare.rb:61:in `analyse_modified_files'
	16: from /Users/adre/.gem/ruby/2.6.3/gems/rubycritic-4.1.0/lib/rubycritic/commands/default.rb:29:in `report'
	15: from /Users/adre/.gem/ruby/2.6.3/gems/rubycritic-4.1.0/lib/rubycritic/reporter.rb:8:in `generate_report'
	14: from /Users/adre/.gem/ruby/2.6.3/gems/rubycritic-4.1.0/lib/rubycritic/reporter.rb:8:in `each'
	13: from /Users/adre/.gem/ruby/2.6.3/gems/rubycritic-4.1.0/lib/rubycritic/reporter.rb:9:in `block in generate_report'
	12: from /Users/adre/.gem/ruby/2.6.3/gems/rubycritic-4.1.0/lib/rubycritic/generators/html_report.rb:20:in `generate_report'
	11: from /Users/adre/.gem/ruby/2.6.3/gems/rubycritic-4.1.0/lib/rubycritic/generators/html_report.rb:33:in `create_directories_and_files'
	10: from /Users/adre/.gem/ruby/2.6.3/gems/rubycritic-4.1.0/lib/rubycritic/generators/html_report.rb:33:in `each'
	 9: from /Users/adre/.gem/ruby/2.6.3/gems/rubycritic-4.1.0/lib/rubycritic/generators/html_report.rb:35:in `block in create_directories_and_files'
	 8: from /Users/adre/.gem/ruby/2.6.3/gems/rubycritic-4.1.0/lib/rubycritic/generators/html_report.rb:35:in `open'
	 7: from /Users/adre/.gem/ruby/2.6.3/gems/rubycritic-4.1.0/lib/rubycritic/generators/html_report.rb:36:in `block (2 levels) in create_directories_and_files'
	 6: from /Users/adre/.gem/ruby/2.6.3/gems/rubycritic-4.1.0/lib/rubycritic/generators/html/code_index.rb:27:in `render'
	 5: from /Users/adre/.rubies/ruby-2.6.3/lib/ruby/2.6.0/erb.rb:901:in `result'
	 4: from /Users/adre/.rubies/ruby-2.6.3/lib/ruby/2.6.0/erb.rb:901:in `eval'
	 3: from (erb):22:in `base_binding'
	 2: from /Users/adre/.gem/ruby/2.6.3/gems/rubycritic-4.1.0/lib/rubycritic/core/analysed_modules_collection.rb:32:in `each'
	 1: from /Users/adre/.gem/ruby/2.6.3/gems/rubycritic-4.1.0/lib/rubycritic/core/analysed_modules_collection.rb:32:in `each'
(erb):28:in `block in base_binding': undefined method `cost' for nil:NilClass (NoMethodError)
$
```

In my case, switching config to `no_browser: true` allowed the process to complete

**Comment by lauratpa** [comment]
I investigated this issue and it seems that the error occurs when there the "feature" branch contains a file that is not present in the "base" branch.

[Here](https://github.com/whitesmith/rubycritic/blob/master/lib/rubycritic/commands/compare.rb#L58) in the `Command::Compare#analyze_modified_files` the files are pulled from the "feature" branch with  `Config.feature_branch_collection.where(SourceControlSystem::Git.modified_files)`.
And [in the html template](https://github.com/whitesmith/rubycritic/blob/master/lib/rubycritic/generators/html/templates/code_index.html.erb#L27) we look for corresponding file within the within the "base" branch files `master_analysed_module = Config.base_branch_collection.find(analysed_module.pathname)`

Which makes sense since we are comparing the files from the two different branches and we need to find the right pairs. But I guess a branch can contain a file that is not present on the second branch and therefore the `master_analysed_module` can be `nil`.

**Comment by akolodii** [comment]
@lauratpa great commit. Will you create PR to this repo?

**Comment by lauratpa** [comment]
@akolodii This this is the PR :) https://github.com/whitesmith/rubycritic/pull/372
