### ISSUE TITLE
wrong number of arguments (given 2, expected 1) (ArgumentError)

### ISSUE THREAD

**Issue by rizalmuthi** [whitesmith/rubycritic#364]
When I run the rubycritics from my terminal passing the folder that I want to check,I got that exception
```
~/s/❯❯❯  rubycritic lib/import/roadblocks                                                                                  
running flay smells

running flog smells
......
running reek smells
......
running complexity
......
running attributes
......
running churn
Traceback (most recent call last):
	21: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/bin/rubycritic:23:in `<main>'
	20: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/bin/rubycritic:23:in `load'
	19: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/bin/rubycritic:10:in `<top (required)>'
	18: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/cli/application.rb:21:in `execute'
	17: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/commands/default.rb:19:in `execute'
	16: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/commands/default.rb:24:in `critique'
	15: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/analysers_runner.rb:29:in `run'
	14: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/analysers_runner.rb:29:in `each'
	13: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/analysers_runner.rb:32:in `block in run'
	12: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/analysers/churn.rb:17:in `run'
	11: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/core/analysed_modules_collection.rb:32:in `each'
	10: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/core/analysed_modules_collection.rb:32:in `each'
	 9: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/analysers/churn.rb:18:in `block in run'
	 8: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/source_control_systems/git.rb:37:in `revisions_count'
	 7: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/source_control_systems/git.rb:33:in `churn'
	 6: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/source_control_systems/git.rb:33:in `new'
	 5: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/source_control_systems/git/churn.rb:29:in `initialize'
	 4: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/source_control_systems/git/churn.rb:47:in `call'
	 3: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/source_control_systems/git/churn.rb:47:in `each'
	 2: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/source_control_systems/git/churn.rb:47:in `block in call'
	 1: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/source_control_systems/git/churn.rb:59:in `process_line'
/Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/source_control_systems/git/churn.rb:72:in `process_file': wrong number of arguments (given 2, expected 1) (ArgumentError)
````

More information:
I did install it directly
```
 gem install rubycritic
```

My ruby version
```
 ruby -v
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]
```

The gem version
```
 rubycritic -v                                                                                                                                   
RubyCritic 4.5.0
```

**Comment by rizalmuthi** [comment]
The offending code is here: https://github.com/whitesmith/rubycritic/blob/master/lib/rubycritic/source_control_systems/git/churn.rb#L59

I reckon its because of the splat (*) to a method, it destruct the array to multiple arguments instead of 1

**Comment by nunosilva800** [comment]
I'm having a hard time trying to replicate this.
From what I can see it's because of your git history. Would you mind pasting the output of the command here?
https://github.com/whitesmith/rubycritic/blob/master/lib/rubycritic/source_control_systems/git/churn.rb#L44

```
git log --all --date=iso --follow --format='format:date:%x09%ad' --name-status .
```

**Comment by rizalmuthi** [comment]
This is the output
```
date:   2020-06-24 17:35:03 +1000
M       lib/import/roadblocks/invalid_heads_of_hierarchy_roadblock.rb

date:   2020-06-24 17:35:03 +1000
M       lib/import/roadblocks/invalid_heads_of_hierarchy_roadblock.rb

date:   2020-06-24 16:34:50 +1000
M       lib/import/roadblocks/hierarchy_error_roadblock.rb

date:   2020-06-24 15:27:03 +1000
M       lib/import/roadblocks/invalid_heads_of_hierarchy_roadblock.rb

date:   2020-06-22 15:57:04 +1000
M       lib/import/roadblocks/hierarchy_error_roadblock.rb

date:   2020-06-22 14:37:02 +1000
M       lib/import/roadblocks/blocker.rb

date:   2020-06-19 13:35:47 +1000
M       lib/import/roadblocks/blocker.rb

date:   2020-06-22 15:32:18 +1000
A       lib/import/roadblocks/invalid_heads_of_hierarchy_roadblock.rb

date:   2020-06-22 16:35:40 +1000
M       lib/import/roadblocks/hierarchy_error_roadblock.rb

date:   2020-06-22 16:34:20 +1000
M       lib/import/roadblocks/blocker.rb

date:   2020-06-22 15:32:18 +1000
A       lib/import/roadblocks/invalid_heads_of_hierarchy_roadblock.rb

date:   2020-02-12 16:16:30 +1100
M       lib/import/roadblocks/hierarchy_error_roadblock.rb

date:   2019-07-03 15:10:33 +1000
M       lib/import/roadblocks/blocker.rb

date:   2019-07-03 13:35:53 +1000
M       lib/import/roadblocks/blocker.rb
M       lib/import/roadblocks/deactivated_employee_roadblock.rb
M       lib/import/roadblocks/employee_id_swap_roadblock.rb
M       lib/import/roadblocks/hierarchy_error_roadblock.rb

date:   2019-07-03 10:11:53 +1000
M       lib/import/roadblocks/blocker.rb
M       lib/import/roadblocks/deactivated_employee_roadblock.rb

date:   2019-07-02 16:35:20 +1000
M       lib/import/roadblocks/blocker.rb
M       lib/import/roadblocks/deactivated_employee_roadblock.rb
M       lib/import/roadblocks/employee_id_swap_roadblock.rb
M       lib/import/roadblocks/hierarchy_error_roadblock.rb

date:   2019-05-24 13:37:51 +1000
M       lib/import/roadblocks/hierarchy_error_roadblock.rb

date:   2019-05-24 09:35:07 +1000
M       lib/import/roadblocks/hierarchy_error_roadblock.rb

date:   2019-05-15 15:01:20 +1000
M       lib/import/roadblocks/employee_id_swap_roadblock.rb
M       lib/import/roadblocks/hierarchy_error_roadblock.rb

date:   2019-05-15 14:13:01 +1000
M       lib/import/roadblocks/blocker.rb
A       lib/import/roadblocks/hierarchy_error_roadblock.rb

date:   2018-12-07 14:17:05 +1100
M       lib/import/roadblocks/employee_id_swap_roadblock.rb

date:   2018-12-03 09:30:26 +1100
M       lib/import/roadblocks/deactivated_employee_roadblock.rb
M       lib/import/roadblocks/employee_id_swap_roadblock.rb

date:   2018-11-21 10:35:27 +1100
M       lib/import/roadblocks/employee_id_swap_roadblock.rb

date:   2018-11-20 15:30:23 +1100
M       lib/import/roadblocks/blocker.rb
M       lib/import/roadblocks/deactivated_employee_roadblock.rb
M       lib/import/roadblocks/employee_id_swap_roadblock.rb

date:   2018-11-08 15:03:33 +1100
M       lib/import/roadblocks/employee_id_swap_roadblock.rb

date:   2018-10-18 13:33:01 +1100
M       lib/import/roadblocks/employee_id_swap_roadblock.rb

date:   2018-10-17 18:21:24 +1100
M       lib/import/roadblocks/deactivated_employee_roadblock.rb
M       lib/import/roadblocks/employee_id_swap_roadblock.rb

date:   2018-09-27 10:11:05 +1000
M       lib/import/roadblocks/blocker.rb
M       lib/import/roadblocks/deactivated_employee_roadblock.rb
M       lib/import/roadblocks/employee_id_swap_roadblock.rb
M       lib/import/roadblocks/roadblock_result.rb

date:   2018-09-26 13:38:48 +1000
D       lib/import/roadblocks/roadblocks.rb
D       lib/import/roadblocks/runner.rb

date:   2018-09-26 13:30:50 +1000
A       lib/import/roadblocks/blocker.rb

date:   2018-09-26 13:06:37 +1000
M       lib/import/roadblocks/employee_id_swap_roadblock.rb

date:   2018-09-26 11:27:01 +1000
M       lib/import/roadblocks/deactivated_employee_roadblock.rb

date:   2018-09-24 11:59:39 +1000
M       lib/import/roadblocks/runner.rb

date:   2018-09-24 11:46:10 +1000
M       lib/import/roadblocks/roadblocks.rb
M       lib/import/roadblocks/runner.rb

date:   2018-09-24 10:40:26 +1000
M       lib/import/roadblocks/runner.rb

date:   2018-09-21 16:38:59 +1000
M       lib/import/roadblocks/employee_id_swap_roadblock.rb

date:   2018-09-20 16:55:30 +1000
M       lib/import/roadblocks/runner.rb

date:   2018-09-17 16:02:34 +1000
M       lib/import/roadblocks/employee_id_swap_roadblock.rb
A       lib/import/roadblocks/runner.rb

date:   2018-09-11 15:11:21 +1000
M       lib/import/roadblocks/deactivated_employee_roadblock.rb
M       lib/import/roadblocks/employee_id_swap_roadblock.rb
M       lib/import/roadblocks/roadblocks.rb

date:   2018-09-11 12:19:29 +1000
M       lib/import/roadblocks/deactivated_employee_roadblock.rb
M       lib/import/roadblocks/roadblocks.rb

date:   2018-09-11 12:12:46 +1000
M       lib/import/roadblocks/deactivated_employee_roadblock.rb
M       lib/import/roadblocks/employee_id_swap_roadblock.rb

date:   2018-09-11 11:59:28 +1000
M       lib/import/roadblocks/deactivated_employee_roadblock.rb
M       lib/import/roadblocks/employee_id_swap_roadblock.rb
A       lib/import/roadblocks/roadblock_result.rb

date:   2018-09-11 10:55:24 +1000
A       lib/import/roadblocks/roadblocks.rb

date:   2018-09-10 15:47:14 +1000
A       lib/import/roadblocks/deactivated_employee_roadblock.rb
A       lib/import/roadblocks/employee_id_swap_roadblock.rb
```

**Comment by nunosilva800** [comment]
Odd, that looks ok.
Let's dig deeper shall we? 😄 

Can you run this in IRB, under that repository?

```ruby
def process_line(line)
    operation, *rest = line.split("\t")

    case operation
    when /^date:/
        return nil
    when /^R/
        return nil
    else
        return rest.length > 1 ? line : nil
    end
end

log = `git log --all --date=iso --follow --format='format:date:%x09%ad' --name-status .`
log.split("\n").reject(&:empty?).map { |line| process_line(line) }.compact
```

This should output the lines in your `git log` that  are not expected by the code.
That could give us a hint at what is happening.

Btw, which `git` version are you using?

**Comment by rizalmuthi** [comment]
```
~/s/❯❯❯ git --version                                                                                                 
git version 2.20.
````

This is what I got after execute the last part
```
[7] pry(#<Pry::CLI>)> log.split("\n").reject(&:empty?).map { |line| process_line(line) }.compact
=> []
```

its strange.
So I opened up the gem and print out the **line** and the **rest**
```
["docker-compose.standalone.extend.yml"]
"M\tREADME.md"
["README.md"]
"M\tbin/launch"
["bin/launch"]
"C051\tdocker-compose.yml\tdocker-compose.standalone.extend.yml"
["docker-compose.yml", "docker-compose.standalone.extend.yml"]
Traceback (most recent call last):
	21: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/bin/rubycritic:23:in `<main>'
	20: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/bin/rubycritic:23:in `load'
	19: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/bin/rubycritic:10:in `<top (required)>'
	18: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/cli/application.rb:21:in `execute'
	17: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/commands/default.rb:19:in `execute'
	16: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/commands/default.rb:24:in `critique'
	15: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/analysers_runner.rb:29:in `run'
	14: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/analysers_runner.rb:29:in `each'
	13: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/analysers_runner.rb:32:in `block in run'
	12: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/analysers/churn.rb:17:in `run'
	11: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/core/analysed_modules_collection.rb:32:in `each'
	10: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/core/analysed_modules_collection.rb:32:in `each'
	 9: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/analysers/churn.rb:18:in `block in run'
	 8: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/source_control_systems/git.rb:37:in `revisions_count'
	 7: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/source_control_systems/git.rb:33:in `churn'
	 6: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/source_control_systems/git.rb:33:in `new'
	 5: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/source_control_systems/git/churn.rb:29:in `initialize'
	 4: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/source_control_systems/git/churn.rb:48:in `call'
	 3: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/source_control_systems/git/churn.rb:48:in `each'
	 2: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/source_control_systems/git/churn.rb:48:in `block in call'
	 1: from /Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/source_control_systems/git/churn.rb:63:in `process_line'
/Users/muhammad.muthi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rubycritic-4.5.0/lib/rubycritic/source_control_systems/git/churn.rb:76:in `process_file': wrong number of arguments (given 2, expected 1) (ArgumentError)
```
The last **rest** returns 2 variable inside the array

**Comment by nunosilva800** [comment]
So the `C051` is the term not being handled by the `case operation` statement. 
No idea what that means.. maybe a mix of `R`ename and `M`odified.

If that is the case (and it looks like it because of the two file names), then updating the `when` clause to : 
```
when /^[RC]/
            process_rename(*rest)
```

Would fix this. Wanna summit a fix please? 😄

**Comment by rizalmuthi** [comment]
@nunosilva800 sure, I can submit a fix. I will do that 👍

**Comment by rizalmuthi** [comment]
@nunosilva800 Submitted a PR: https://github.com/whitesmith/rubycritic/pull/365
Cheers

**Comment by nunosilva800** [comment]
Published! https://rubygems.org/gems/rubycritic/versions/4.5.1

🙏
