### ISSUE TITLE
Issue trying to parse a block with named parameters

### ISSUE THREAD

**Issue by bankair** [whitesmith/rubycritic#40]
|            | Version |
|------------|---------|
| Ruby       | 2.0.0p353   |
| RubyCritic | 1.1.1   |

While trying to parse a ruby block with named parameters like follow:

``` ruby
class Foo
  %w(debug info warn error).each do |level|
    define_method(level.to_sym) do |msg = nil, opA: nil, opB: nil, opC: nil, &block|
      puts("[#{level}] #{msg.inspect}")
    end
  end
end

Foo.new.info('message') # => [info] "message"
```

I got some ugly error message:

```
tmp$ rubycritic test.rb
Rubycritic requires a Git repository.
  not yet 35 [s(:array, s(:kwarg, :opA, s(:nil))), ",", s(:array, s(:kwarg, :opB, s(:nil)))] => s(:array, s(:kwarg, :opA, s(:nil)))
  skipping test.rb
/usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/ruby_parser-3.4.1/lib/ruby_parser_extras.rb:107:in `debug20': not yet 35 [s(:array, s(:kwarg, :opA, s(:nil))), ",", s(:array, s(:kwarg, :opB, s(:nil)))] => s(:array, s(:kwarg, :opA, s(:nil))) (RuntimeError)
	from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/ruby_parser-3.4.1/lib/ruby20_parser.rb:6417:in `_reduce_559'
	from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/2.0.0/racc/parser.rb:258:in `_racc_do_parse_c'
	from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/2.0.0/racc/parser.rb:258:in `do_parse'
	from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/ruby_parser-3.4.1/lib/ruby_parser_extras.rb:1019:in `block in process'
	from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
	from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/ruby_parser-3.4.1/lib/ruby_parser_extras.rb:1007:in `process'
	from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/ruby_parser-3.4.1/lib/ruby_parser_extras.rb:1320:in `process'
	from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/flog-4.2.1/lib/flog.rb:219:in `flog_ruby!'
	from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/flog-4.2.1/lib/flog.rb:189:in `flog_ruby'
	from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/flog-4.2.1/lib/flog.rb:177:in `block in flog'
	from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/flog-4.2.1/lib/flog.rb:172:in `each'
	from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/flog-4.2.1/lib/flog.rb:172:in `flog'
	from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rubycritic-1.1.1/lib/rubycritic/analysers/smells/flog.rb:26:in `add_smells_to'
	from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rubycritic-1.1.1/lib/rubycritic/analysers/smells/flog.rb:18:in `block in run'
	from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rubycritic-1.1.1/lib/rubycritic/analysers/smells/flog.rb:17:in `each'
	from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rubycritic-1.1.1/lib/rubycritic/analysers/smells/flog.rb:17:in `run'
	from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rubycritic-1.1.1/lib/rubycritic/analysers_runner.rb:26:in `block in run'
	from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rubycritic-1.1.1/lib/rubycritic/analysers_runner.rb:25:in `each'
	from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rubycritic-1.1.1/lib/rubycritic/analysers_runner.rb:25:in `run'
	from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rubycritic-1.1.1/lib/rubycritic/orchestrator.rb:15:in `critique'
	from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rubycritic-1.1.1/lib/rubycritic/cli.rb:37:in `execute'
	from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rubycritic-1.1.1/bin/rubycritic:5:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.0.0-p353/bin/rubycritic:23:in `load'
	from /usr/local/var/rbenv/versions/2.0.0-p353/bin/rubycritic:23:in `<main>'
```
I did not find any other issue that seemed to be related to this.

As we are currently using rubycritic to get code quality report at work, we would be very thankful of any tip to work around this issue.

Many thanks in advance, guys, and congrat's for that tool, it's really useful !

**Comment by bankair** [comment]
Oh, and by the way, that ruby code seems to be legit (it runs and print 'info "message"', as expected.

**Comment by guilhermesimoes** [comment]
Unfortunately this is an issue in [ruby_parser/issues#180][1] so there's nothing we can do about it :(

I'm going to find a way to catch these parsing errors though.

[1]: https://github.com/seattlerb/ruby_parser/issues/180

**Comment by bf4** [comment]
Or switch to https://github.com/whitequark/parser :)

**Comment by guilhermesimoes** [comment]
Oh, I'm using `parser` alright, it's definitely the best cross-Ruby parser. But as you can see from the stack trace, this is a `Flog` (and `Flay`) dependency :(

I've been thinking about rewriting `Flay` from scratch using `parser` for a while now. `Flay` does not return the line where the code duplication ends because `ruby_parser` does not provide that information. And I'd love to have that in RubyCritic.

But to truly remove the `ruby_parser` dependency, we'd have to rewrite Flog as well :(

**Comment by bf4** [comment]
And probably need to defeat ryan davis in hand to hand combat....

**Comment by bankair** [comment]
Ermm... This start to looks dangerous. Who needs keyword parameters in block, anyway ? :)

**Comment by guilhermesimoes** [comment]
> And probably need to defeat ryan davis in hand to hand combat....

Ahaha I watch most of his GitHub repos, so I'm already aware... I wouldn't want that, no sir aha

If I ever rewrite Flay, I'll let you know ;)

**Comment by bf4** [comment]
Well, that bug is now fixed in https://github.com/seattlerb/ruby_parser/commit/a1750d474c4309a9166afc63cfcde35a6f8241ad

**Comment by bankair** [comment]
Great, can't wait to see that fix included in the next rubycritic release.

Thanks, guys !
