### ISSUE TITLE
flog dependency error but only when running on CI:

### ISSUE THREAD

**Issue by icehaku** [whitesmith/rubycritic#415]
ruby 2.7.0p0
Error: 
>binread': Is a directory @ io_fread

**Full Trace:**

`bundle exec rubycritic

/root/integration-framework/backend/vendor/bundle/ruby/2.7.0/gems/ruby_parser-3.19.1/lib/ruby_parser_extras.rb:1314: warning: regular expression has redundant nested repeat operator '+': /a{1,}+/
/root/integration-framework/backend/vendor/bundle/ruby/2.7.0/gems/ruby_parser-3.19.1/lib/ruby_parser_extras.rb:1314: warning: character class has ']' without escape: /[]]/
  Is a directory @ io_fread - vendor/bundle/ruby/2.7.0/gems/path_expander-1.1.1/test/bad_named_dir.rb
  skipping vendor/bundle/ruby/2.7.0/gems/path_expander-1.1.1/test/bad_named_dir.rb
  vendor/bundle/ruby/2.7.0/gems/kwalify-0.7.2/test/data/users-guide/howto-validation-with-parsing.rb:14 :: parse error on value "Yaml" (tSYMBOL)
  skipping vendor/bundle/ruby/2.7.0/gems/kwalify-0.7.2/test/data/users-guide/howto-validation-with-parsing.rb
  vendor/bundle/ruby/2.7.0/gems/pundit-2.2.0/lib/generators/pundit/policy/templates/policy.rb:1 :: parse error on value "<" (tLT)
  skipping vendor/bundle/ruby/2.7.0/gems/pundit-2.2.0/lib/generators/pundit/policy/templates/policy.rb
  vendor/bundle/ruby/2.7.0/gems/pundit-2.2.0/lib/generators/rspec/templates/policy_spec.rb:1 :: parse error on value "spec" (tIDENTIFIER)
  skipping vendor/bundle/ruby/2.7.0/gems/pundit-2.2.0/lib/generators/rspec/templates/policy_spec.rb
  vendor/bundle/ruby/2.7.0/gems/pundit-2.2.0/lib/generators/test_unit/templates/policy_test.rb:3 :: parse error on value "<" (tLT)
  skipping vendor/bundle/ruby/2.7.0/gems/pundit-2.2.0/lib/generators/test_unit/templates/policy_test.rb
running flay smells
...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
running flog smells
........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................../root/integration-framework/backend/vendor/bundle/ruby/2.7.0/gems/ruby_parser-3.19.1/lib/ruby_parser_extras.rb:1314: warning: regular expression has redundant nested repeat operator '+': /a{1,}+/
/root/integration-framework/backend/vendor/bundle/ruby/2.7.0/gems/ruby_parser-3.19.1/lib/ruby_parser_extras.rb:1314: warning: character class has ']' without escape: /[]]/
....................................................................................bundler: failed to load command: rubycritic (/root/integration-framework/backend/vendor/bundle/ruby/2.7.0/bin/rubycritic)
Traceback (most recent call last):
	32: from /var/lang/bin/bundle:23:in `<main>'
	31: from /var/lang/bin/bundle:23:in `load'
	30: from /var/runtime/gems/bundler-2.2.7/exe/bundle:37:in `<top (required)>'
	29: from /var/runtime/gems/bundler-2.2.7/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	28: from /var/runtime/gems/bundler-2.2.7/exe/bundle:49:in `block in <top (required)>'
	27: from /var/runtime/gems/bundler-2.2.7/lib/bundler/cli.rb:24:in `start'
	26: from /var/runtime/gems/bundler-2.2.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	25: from /var/runtime/gems/bundler-2.2.7/lib/bundler/cli.rb:30:in `dispatch'
	24: from /var/runtime/gems/bundler-2.2.7/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	23: from /var/runtime/gems/bundler-2.2.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	22: from /var/runtime/gems/bundler-2.2.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	21: from /var/runtime/gems/bundler-2.2.7/lib/bundler/cli.rb:494:in `exec'
	20: from /var/runtime/gems/bundler-2.2.7/lib/bundler/cli/exec.rb:28:in `run'
	19: from /var/runtime/gems/bundler-2.2.7/lib/bundler/cli/exec.rb:63:in `kernel_load'
	18: from /var/runtime/gems/bundler-2.2.7/lib/bundler/cli/exec.rb:63:in `load'
	17: from /root/integration-framework/backend/vendor/bundle/ruby/2.7.0/bin/rubycritic:23:in `<top (required)>'
	16: from /root/integration-framework/backend/vendor/bundle/ruby/2.7.0/bin/rubycritic:23:in `load'
	15: from /root/integration-framework/backend/vendor/bundle/ruby/2.7.0/gems/rubycritic-4.7.0/bin/rubycritic:10:in `<top (required)>'
	14: from /root/integration-framework/backend/vendor/bundle/ruby/2.7.0/gems/rubycritic-4.7.0/lib/rubycritic/cli/application.rb:21:in `execute'
	13: from /root/integration-framework/backend/vendor/bundle/ruby/2.7.0/gems/rubycritic-4.7.0/lib/rubycritic/commands/default.rb:19:in `execute'
	12: from /root/integration-framework/backend/vendor/bundle/ruby/2.7.0/gems/rubycritic-4.7.0/lib/rubycritic/commands/default.rb:24:in `critique'
	11: from /root/integration-framework/backend/vendor/bundle/ruby/2.7.0/gems/rubycritic-4.7.0/lib/rubycritic/analysers_runner.rb:29:in `run'
	10: from /root/integration-framework/backend/vendor/bundle/ruby/2.7.0/gems/rubycritic-4.7.0/lib/rubycritic/analysers_runner.rb:29:in `each'
	 9: from /root/integration-framework/backend/vendor/bundle/ruby/2.7.0/gems/rubycritic-4.7.0/lib/rubycritic/analysers_runner.rb:32:in `block in run'
	 8: from /root/integration-framework/backend/vendor/bundle/ruby/2.7.0/gems/rubycritic-4.7.0/lib/rubycritic/analysers/smells/flog.rb:20:in `run'
	 7: from /root/integration-framework/backend/vendor/bundle/ruby/2.7.0/gems/rubycritic-4.7.0/lib/rubycritic/core/analysed_modules_collection.rb:32:in `each'
	 6: from /root/integration-framework/backend/vendor/bundle/ruby/2.7.0/gems/rubycritic-4.7.0/lib/rubycritic/core/analysed_modules_collection.rb:32:in `each'
	 5: from /root/integration-framework/backend/vendor/bundle/ruby/2.7.0/gems/rubycritic-4.7.0/lib/rubycritic/analysers/smells/flog.rb:21:in `block in run'
	 4: from /root/integration-framework/backend/vendor/bundle/ruby/2.7.0/gems/rubycritic-4.7.0/lib/rubycritic/analysers/smells/flog.rb:35:in `add_smells_to'
	 3: from /root/integration-framework/backend/vendor/bundle/ruby/2.7.0/gems/flog-4.6.6/lib/flog.rb:168:in `flog'
	 2: from /root/integration-framework/backend/vendor/bundle/ruby/2.7.0/gems/flog-4.6.6/lib/flog.rb:168:in `each'
	 1: from /root/integration-framework/backend/vendor/bundle/ruby/2.7.0/gems/flog-4.6.6/lib/flog.rb:171:in `block in flog'
/root/integration-framework/backend/vendor/bundle/ruby/2.7.0/gems/flog-4.6.6/lib/flog.rb:171:in `binread': Is a directory @ io_fread - vendor/bundle/ruby/2.7.0/gems/path_expander-1.1.1/test/bad_named_dir.rb (Errno::EISDIR)

Exited with code exit status 1
CircleCI received exit code 1`

**Comment by icehaku** [comment]
Running on the local project I don't get this error;

**Comment by icehaku** [comment]
Found the "problem";
Just is case someone is as dumb as me;
My project folder was a mixed setup with a frontend folder and a backend folder.
I was creating the .rubycritic.yml file outside of my backend folder;

The backend is my ruby project folder, so the rubycritic commands runs there;

What I was doing:
> project/.rubycritic.yml
The proper way:
> project/backend/.rubycritic.yml

Because the .rubycritic.yml was in the wrong direct the PATHs I was settings was not being used, and because of that
the rubycritic comand was trying to parse something else in the project and getting the described error.
