### ISSUE TITLE
Analysers running twice in some cases

### ISSUE THREAD

**Issue by jbodah** [whitesmith/rubycritic#94]
Haven't been able to dig into this yet, but it's been happening a lot lately. Will report more as it comes up. Figured I'd post in case others were experiencing this. Seems to happen whenever I destroy the tmp folder:

```
Bodah@jbodah-local 2.1.3p242 ~/repos/rubycritic (master) $ rm -rf tmp
Bodah@jbodah-local 2.1.3p242 ~/repos/rubycritic (master) $ bin/rubycritic lib
running flay smells

running flog smells
..................................................
running reek smells
..................................................
running complexity
..................................................
running attributes
..................................................
running churn
..................................................
running flay smells

running flog smells
..................................................
running reek smells
..................................................
running complexity
..................................................
running attributes
..................................................
running churn
..................................................
New critique at file:///Users/Bodah/repos/rubycritic/tmp/rubycritic/overview.html
Bodah@jbodah-local 2.1.3p242 ~/repos/rubycritic (master) $ vim lib/rubycritic/analysers
analysers/           analysers_runner.rb
Bodah@jbodah-local 2.1.3p242 ~/repos/rubycritic (master) $ vim lib/rubycritic/analysers_runner.rb
Bodah@jbodah-local 2.1.3p242 ~/repos/rubycritic (master) $ rm -rf tmp
Bodah@jbodah-local 2.1.3p242 ~/repos/rubycritic (master) $ bin/rubycritic lib

[22, 31] in /Users/Bodah/repos/rubycritic/lib/rubycritic/analysers_runner.rb
   22:       @paths = paths
   23:     end
   24:
   25:     def run
   26:       require 'rubygems'; require 'byebug'; byebug
=> 27:       ANALYSERS.each do |analyser_class|
   28:         analyser_instance = analyser_class.new(analysed_modules)
   29:         puts "running #{analyser_instance}"
   30:         analyser_instance.run
   31:       end
(byebug) require 'ap'
true
(byebug) ap caller
[
    [ 0] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/helpers/eval.rb:59:in `eval'",
    [ 1] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/helpers/eval.rb:59:in `safe_eval'",
    [ 2] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/helpers/eval.rb:53:in `warning_eval'",
    [ 3] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/helpers/eval.rb:29:in `block in multiple_thread_eval'",
    [ 4] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/helpers/eval.rb:92:in `allowing_other_threads'",
    [ 5] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/helpers/eval.rb:29:in `multiple_thread_eval'",
    [ 6] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/processors/command_processor.rb:164:in `block in run_cmd'",
    [ 7] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/processors/command_processor.rb:169:in `safely'",
    [ 8] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/processors/command_processor.rb:160:in `run_cmd'",
    [ 9] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/processors/command_processor.rb:149:in `repl'",
    [10] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/processors/command_processor.rb:98:in `process_commands'",
    [11] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/processors/command_processor.rb:56:in `at_line'",
    [12] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/context.rb:96:in `at_line'",
    [13] "/Users/Bodah/repos/rubycritic/lib/rubycritic/analysers_runner.rb:27:in `run'",
    [14] "/Users/Bodah/repos/rubycritic/lib/rubycritic/commands/default.rb:19:in `critique'",
    [15] "/Users/Bodah/repos/rubycritic/lib/rubycritic/commands/default.rb:15:in `execute'",
    [16] "/Users/Bodah/repos/rubycritic/lib/rubycritic/cli/application.rb:17:in `execute'",
    [17] "bin/rubycritic:9:in `<main>'"
]
nil
(byebug) c
running flay smells

running flog smells
..................................................
running reek smells
..................................................
running complexity
..................................................
running attributes
..................................................
running churn
..................................................

[22, 31] in /Users/Bodah/repos/rubycritic/lib/rubycritic/analysers_runner.rb
   22:       @paths = paths
   23:     end
   24:
   25:     def run
   26:       ANALYSERS.each do |analyser_class|
=> 27:         analyser_instance = analyser_class.new(analysed_modules)
   28:         puts "running #{analyser_instance}"
   29:         analyser_instance.run
   30:       end
   31:       analysed_modules
(byebug) ap caller
[
    [ 0] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/helpers/eval.rb:59:in `eval'",
    [ 1] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/helpers/eval.rb:59:in `safe_eval'",
    [ 2] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/helpers/eval.rb:53:in `warning_eval'",
    [ 3] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/helpers/eval.rb:29:in `block in multiple_thread_eval'",
    [ 4] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/helpers/eval.rb:92:in `allowing_other_threads'",
    [ 5] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/helpers/eval.rb:29:in `multiple_thread_eval'",
    [ 6] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/processors/command_processor.rb:164:in `block in run_cmd'",
    [ 7] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/processors/command_processor.rb:169:in `safely'",
    [ 8] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/processors/command_processor.rb:160:in `run_cmd'",
    [ 9] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/processors/command_processor.rb:149:in `repl'",
    [10] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/processors/command_processor.rb:98:in `process_commands'",
    [11] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/processors/command_processor.rb:56:in `at_line'",
    [12] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/context.rb:96:in `at_line'",
    [13] "/Users/Bodah/repos/rubycritic/lib/rubycritic/analysers_runner.rb:27:in `run'",
    [14] "/Users/Bodah/repos/rubycritic/lib/rubycritic/revision_comparator.rb:35:in `block in analysed_modules_before'",
    [15] "/Users/Bodah/repos/rubycritic/lib/rubycritic/source_control_systems/git.rb:33:in `travel_to_head'",
    [16] "/Users/Bodah/repos/rubycritic/lib/rubycritic/revision_comparator.rb:34:in `analysed_modules_before'",
    [17] "/Users/Bodah/repos/rubycritic/lib/rubycritic/revision_comparator.rb:19:in `set_statuses'",
    [18] "/Users/Bodah/repos/rubycritic/lib/rubycritic/commands/default.rb:20:in `critique'",
    [19] "/Users/Bodah/repos/rubycritic/lib/rubycritic/commands/default.rb:15:in `execute'",
    [20] "/Users/Bodah/repos/rubycritic/lib/rubycritic/cli/application.rb:17:in `execute'",
    [21] "bin/rubycritic:9:in `<main>'"
]
nil
(byebug) c
running flay smells

running flog smells
..................................................
running reek smells
..................................................
running complexity
..................................................
running attributes
..................................................
running churn
..................................................
New critique at file:///Users/Bodah/repos/rubycritic/tmp/rubycritic/overview.html
```

**Comment by jbodah** [comment]
<img width="697" alt="1__bash" src="https://cloud.githubusercontent.com/assets/6093002/12158723/81576e04-b4aa-11e5-8eea-a5e777e01ba1.png">

**Comment by jbodah** [comment]
```
Bodah@jbodah-local 2.1.3p242 ~/repos/rubycritic (master) $ rm -rf tmp
Bodah@jbodah-local 2.1.3p242 ~/repos/rubycritic (master) $ bin/rubycritic lib
running flay smells

running flog smells
..................................................
running reek smells
..................................................
running complexity
..................................................
running attributes
..................................................
running churn
..................................................
running flay smells

running flog smells
..................................................
running reek smells
..................................................
running complexity
..................................................
running attributes
..................................................
running churn
..................................................
New critique at file:///Users/Bodah/repos/rubycritic/tmp/rubycritic/overview.html
Bodah@jbodah-local 2.1.3p242 ~/repos/rubycritic (master) $ vim lib/rubycritic/analysers
analysers/           analysers_runner.rb
Bodah@jbodah-local 2.1.3p242 ~/repos/rubycritic (master) $ vim lib/rubycritic/analysers_runner.rb
Bodah@jbodah-local 2.1.3p242 ~/repos/rubycritic (master) $ rm -rf tmp
Bodah@jbodah-local 2.1.3p242 ~/repos/rubycritic (master) $ bin/rubycritic lib

[22, 31] in /Users/Bodah/repos/rubycritic/lib/rubycritic/analysers_runner.rb
   22:       @paths = paths
   23:     end
   24:
   25:     def run
   26:       require 'rubygems'; require 'byebug'; byebug
=> 27:       ANALYSERS.each do |analyser_class|
   28:         analyser_instance = analyser_class.new(analysed_modules)
   29:         puts "running #{analyser_instance}"
   30:         analyser_instance.run
   31:       end
(byebug) require 'ap'
true
(byebug) ap caller
[
    [ 0] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/helpers/eval.rb:59:in `eval'",
    [ 1] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/helpers/eval.rb:59:in `safe_eval'",
    [ 2] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/helpers/eval.rb:53:in `warning_eval'",
    [ 3] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/helpers/eval.rb:29:in `block in multiple_thread_eval'",
    [ 4] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/helpers/eval.rb:92:in `allowing_other_threads'",
    [ 5] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/helpers/eval.rb:29:in `multiple_thread_eval'",
    [ 6] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/processors/command_processor.rb:164:in `block in run_cmd'",
    [ 7] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/processors/command_processor.rb:169:in `safely'",
    [ 8] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/processors/command_processor.rb:160:in `run_cmd'",
    [ 9] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/processors/command_processor.rb:149:in `repl'",
    [10] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/processors/command_processor.rb:98:in `process_commands'",
    [11] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/processors/command_processor.rb:56:in `at_line'",
    [12] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/context.rb:96:in `at_line'",
    [13] "/Users/Bodah/repos/rubycritic/lib/rubycritic/analysers_runner.rb:27:in `run'",
    [14] "/Users/Bodah/repos/rubycritic/lib/rubycritic/commands/default.rb:19:in `critique'",
    [15] "/Users/Bodah/repos/rubycritic/lib/rubycritic/commands/default.rb:15:in `execute'",
    [16] "/Users/Bodah/repos/rubycritic/lib/rubycritic/cli/application.rb:17:in `execute'",
    [17] "bin/rubycritic:9:in `<main>'"
]
nil
(byebug) c
running flay smells

running flog smells
..................................................
running reek smells
..................................................
running complexity
..................................................
running attributes
..................................................
running churn
..................................................

[22, 31] in /Users/Bodah/repos/rubycritic/lib/rubycritic/analysers_runner.rb
   22:       @paths = paths
   23:     end
   24:
   25:     def run
   26:       ANALYSERS.each do |analyser_class|
=> 27:         analyser_instance = analyser_class.new(analysed_modules)
   28:         puts "running #{analyser_instance}"
   29:         analyser_instance.run
   30:       end
   31:       analysed_modules
(byebug) ap caller
[
    [ 0] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/helpers/eval.rb:59:in `eval'",
    [ 1] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/helpers/eval.rb:59:in `safe_eval'",
    [ 2] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/helpers/eval.rb:53:in `warning_eval'",
    [ 3] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/helpers/eval.rb:29:in `block in multiple_thread_eval'",
    [ 4] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/helpers/eval.rb:92:in `allowing_other_threads'",
    [ 5] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/helpers/eval.rb:29:in `multiple_thread_eval'",
    [ 6] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/processors/command_processor.rb:164:in `block in run_cmd'",
    [ 7] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/processors/command_processor.rb:169:in `safely'",
    [ 8] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/processors/command_processor.rb:160:in `run_cmd'",
    [ 9] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/processors/command_processor.rb:149:in `repl'",
    [10] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/processors/command_processor.rb:98:in `process_commands'",
    [11] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/processors/command_processor.rb:56:in `at_line'",
    [12] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/context.rb:96:in `at_line'",
    [13] "/Users/Bodah/repos/rubycritic/lib/rubycritic/analysers_runner.rb:27:in `run'",
    [14] "/Users/Bodah/repos/rubycritic/lib/rubycritic/revision_comparator.rb:35:in `block in analysed_modules_before'",
    [15] "/Users/Bodah/repos/rubycritic/lib/rubycritic/source_control_systems/git.rb:33:in `travel_to_head'",
    [16] "/Users/Bodah/repos/rubycritic/lib/rubycritic/revision_comparator.rb:34:in `analysed_modules_before'",
    [17] "/Users/Bodah/repos/rubycritic/lib/rubycritic/revision_comparator.rb:19:in `set_statuses'",
    [18] "/Users/Bodah/repos/rubycritic/lib/rubycritic/commands/default.rb:20:in `critique'",
    [19] "/Users/Bodah/repos/rubycritic/lib/rubycritic/commands/default.rb:15:in `execute'",
    [20] "/Users/Bodah/repos/rubycritic/lib/rubycritic/cli/application.rb:17:in `execute'",
    [21] "bin/rubycritic:9:in `<main>'"
]
nil
(byebug) c
running flay smells

running flog smells
..................................................
running reek smells
..................................................
running complexity
..................................................
running attributes
..................................................
running churn
..................................................
New critique at file:///Users/Bodah/repos/rubycritic/tmp/rubycritic/overview.html
```

**Comment by jbodah** [comment]
Looks like it might be trying to compare my working copy with my git head, but my working copy is totally clean, so this is just running the same thing again

**Comment by troessner** [comment]
Confirmed, happens on my machine as well.

**Comment by Onumis** [comment]
Calling `rubycritic` outside the repo:
```
nuno@pc:~/projects/whitesmith$ rubycritic -v
RubyCritic 2.4.1
nuno@pc:~/projects/whitesmith$ rubycritic rubycritic/lib/
RubyCritic can provide more feedback if you use a Git or Mercurial repository.
running flay smells

running flog smells
.................................................
running reek smells
.................................................
running complexity
.................................................
running attributes
.................................................
running churn
.................................................
New critique at file:///home/nuno/projects/whitesmith/tmp/rubycritic/overview.html
```

Calling rubycritic inside the repo:
```
nuno@pc:~/projects/whitesmith/rubycritic$ rubycritic -v
RubyCritic 2.4.1
nuno@pc:~/projects/whitesmith/rubycritic$ rubycritic lib/
running flay smells

running flog smells
.................................................
running reek smells
.................................................
running complexity
.................................................
running attributes
.................................................
running churn
.................................................
running flay smells

running flog smells
.................................................
running reek smells
.................................................
running complexity
.................................................
running attributes
.................................................
running churn
.................................................
New critique at file:///home/nuno/projects/whitesmith/rubycritic/tmp/rubycritic/overview.html

```

Could this be something introduced with: #88 ?

**Comment by Onumis** [comment]
It can also just be what @jbodah said, and we've always had this problem when with git repositories and only noticing it now due to the cmd line output...

**Comment by Onumis** [comment]
I think I've tracked this down to a culprit: [`RevisionComparator`](/whitesmith/rubycritic/blob/master/lib/rubycritic/revision_comparator.rb)

This bug seems to happen only when RubyCritic runs in the "default" mode.
The only difference with the "ci" mode is that the `RevisionComparator` does not run when in "ci" mode.

`RevisionComparator` checks if the analysed code is under a source control system and attempts to compare the current run with a previous one.
The previous revision is stored at: `tmp/rubycritic/snapshots/:version/:md5_hex/:reference`
In the case this previous revision is not found:

1. stash
2. a new instance of `AnalysersRunner` is ran on the code
3. stash pop
4. store the revision and proceed with the comparison

So, the solution might be to simply not run the analysis again if there is no previous revision, but I'm not sure if this is the best solution.
Maybe we should just suppress the console output on this second run...

What do you think?

**Comment by jbodah** [comment]
> So, the solution might be to simply not run the analysis again if there is no previous revision, but I'm not sure if this is the best solution.

It would be great if it could cache the initial run regardless if I have a working copy to stash or not. Consider this scenario.

* Working copy is clean, run rubycritic
* Single analyser runs, should cache run unless disabled
* I add code to my working copy, run rubycritic
* Single analyser should run; my cached results from last run (which should be on my HEAD rev) should be used for revision comparison, and an analyser should also run on my working copy

I would think the spec for this would look something like:

Given I'm using CI Mode (no rev comparison)
Then never cache

Given I'm not using CI Mode (rev comparison)
And I have clean working copy
Then should run once
And should cache

Given I'm not using CI Mode
And I have clean working copy
And I just ran rubycritic
Then should not run; should use cached

Given I'm not using CI Mode
And I have a dirty working copy
Then should run twice
And cache revision

Given I'm not using CI Mode
And I have a dirty working copy
And I have a cached HEAD revision run
Then should run once (revision hits cache)

**Comment by jbodah** [comment]
> Maybe we should just suppress the console output on this second run...

I think I'd prefer a log message saying what it's doing instead. I think running twice is fine as long as I know why

**Comment by troessner** [comment]
I completely agree with @jbodah
